cloud:
  aws:
    region:
      static: us-west-2
    stack:
      autor: false
    credentials:
      access-Key: AKIAY43AVH6VOF2ATJJV
      secret-Key: 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

logging:
  level:
    con:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error